#6.1.4 Generate Random Latitudes and Longitudes

In [15]:
# Import the random module.
import random

#The randint() Function

In [14]:
random.randint(-90, 90)

-50

#The random() Function

In [10]:
random.random()

0.6485466253674074

In [16]:
random_number = random.randint(-90, 89) + random.random()
random_number

75.05663811135229

In [21]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1
latitudes

[86.86392488991801,
 -17.13677184236255,
 48.991489871404035,
 35.226562800769685,
 16.652801566511837,
 -60.60860745593755,
 25.18708262244055,
 25.072967517589817,
 -29.955251602856908,
 -8.549850456622416]

#The randrange() Function

In [22]:
random.randrange(-90, 90, step=1)

83

In [23]:
random.randrange(-90, 90, step=3)

0

In [ ]:
#The uniform() Function

In [24]:
random.uniform(-90, 90)

-88.95856262981233

In [ ]:
#The NumPy and random Modules

In [25]:
# Import the NumPy module.
import numpy as np

In [26]:
np.random.uniform(-90.000, 90.000)

31.15391582771572

In [27]:
#Another option is to write the parameters as
np.random.uniform(low=-90, high=90)

-8.320048323163206

In [28]:
np.random.uniform(-90.000, 90.000, size=50)

array([-33.31076291, -77.43895607,  89.50481778, -18.72582164,
        -1.38787977,  -2.12539127,  -7.39234515,  40.76849994,
       -27.13634152,  35.43526236, -57.77612109, -41.45411718,
       -45.0194762 , -22.71095535, -58.87660578,  28.85036027,
        84.80411996,  -6.21968686, -41.94313185, -89.64695332,
       -67.42017888, -81.5798893 ,  88.9361362 ,  30.60521752,
        28.278719  , -23.54009143, -71.49231473, -34.61469351,
        28.91120917,  -5.31236449, -68.47892867,  87.31915597,
       -56.03797492,  80.28430535,  29.17785361, -56.72812127,
       -67.69036689, -53.52354693,   5.26869532, -83.80863218,
        45.63132951, -42.56283029,  16.56834627, -35.88078635,
       -53.32237375,   4.2183462 ,  60.61662557,  30.99928972,
       -18.56298295,   1.99155265])

In [29]:
# Import timeit.
import timeit

In [30]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

48.5 µs ± 585 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

4.45 ms ± 70.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [32]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 87.73681911,  -7.47322284, -80.61123508, ...,  16.31057148,
       -46.13155189, -35.01850028])

In [33]:
#skilldrill

In [37]:
%timeit np.random.uniform(50.000, 100.000, size=1500)

48.2 µs ± 558 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [38]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(50.000, 100.000) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

4.55 ms ± 253 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [39]:
np.random.uniform(50.000, 100.000, size=1500)

array([76.64260016, 63.66736919, 74.61667289, ..., 64.72715263,
       68.05799273, 72.04701367])